server:
  port: 9008

spring:
  rabbitmq:
    host: 192.168.8.33
    port: 5672

aliyun:
  sms:
    accessKeyId: #创建的accesskey中的AccessKey ID
    accessKeySecret: #创建的accesskey中的Access Key Secret
    template_code: SMS_182682742 #模板管理中的模板CODE
    sign_name: OATS #签名管理中的签名