server:
  port: 9010

spring:
  application:
    name: pang-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.33:3336/tensquare_friend?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
#jwt
jwt:
  config:
    key: pang
    ttl: 360000000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
